import { NextRequest, NextResponse } from 'next/server';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { fetchIndicator } from '@/lib/worldbank';
import { FREE_INDICATORS, PRO_INDICATORS, INDICATORS } from '@/lib/indicators';
import { verifyToken, TOKEN_COOKIE } from '@/lib/auth';

function formatValue(val: number | null, format: string): string {
  if (val === null) return 'N/A';
  switch (format) {
    case 'billions':
      return `$${(val / 1e9).toFixed(1)}B`;
    case 'millions':
      return `${(val / 1e6).toFixed(1)}M`;
    case 'percent':
      return `${val.toFixed(1)}%`;
    default:
      return val >= 1000 ? val.toLocaleString('en-US', { maximumFractionDigits: 1 }) : val.toFixed(1);
  }
}

export async function GET(request: NextRequest) {
  const { searchParams } = request.nextUrl;
  const countriesParam = searchParams.get('countries');
  const premium = searchParams.get('premium') === 'true';

  if (!countriesParam) {
    return NextResponse.json({ error: 'Missing countries parameter' }, { status: 400 });
  }

  const countryCodes = countriesParam.split(',').map((c) => c.trim().toUpperCase()).slice(0, 10);
  if (countryCodes.length < 1) {
    return NextResponse.json({ error: 'At least one country required' }, { status: 400 });
  }

  // Check Pro status
  const token = request.cookies.get(TOKEN_COOKIE)?.value;
  const isPro = token ? !!verifyToken(token) : false;
  const fullReport = isPro || premium;

  const indicators = fullReport ? INDICATORS : FREE_INDICATORS;

  // Fetch all indicator data
  const allData: {
    indicator: { id: string; name: string; format: string };
    countries: Record<string, { countryName: string; data: { year: string; value: number | null }[] }>;
  }[] = [];

  for (const ind of indicators) {
    try {
      const raw = await fetchIndicator(countryCodes, ind.id);
      const grouped: Record<string, { countryName: string; data: { year: string; value: number | null }[] }> = {};
      for (const item of raw) {
        if (!grouped[item.countryCode]) {
          grouped[item.countryCode] = { countryName: item.countryName, data: [] };
        }
        grouped[item.countryCode].data.push({ year: item.date, value: item.value });
      }
      for (const code of Object.keys(grouped)) {
        grouped[code].data.sort((a, b) => a.year.localeCompare(b.year));
      }
      allData.push({ indicator: { id: ind.id, name: ind.name, format: ind.format }, countries: grouped });
    } catch {
      // skip failed indicators
    }
  }

  if (allData.length === 0) {
    return NextResponse.json({ error: 'No data available' }, { status: 404 });
  }

  // Get country names from data
  const countryNames: Record<string, string> = {};
  for (const d of allData) {
    for (const [code, info] of Object.entries(d.countries)) {
      if (!countryNames[code]) countryNames[code] = info.countryName;
    }
  }

  const titleCountries = countryCodes.map((c) => countryNames[c] || c).join(' vs ');
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // Generate PDF
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // --- Cover Page ---
  doc.setFillColor(30, 64, 175); // blue-800
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.text('Economic Comparison Report', pageWidth / 2, 80, { align: 'center' });

  doc.setFontSize(20);
  doc.text(titleCountries, pageWidth / 2, 100, { align: 'center', maxWidth: pageWidth - 40 });

  doc.setFontSize(12);
  doc.setTextColor(191, 219, 254); // blue-200
  doc.text(`Generated by CountryCompare`, pageWidth / 2, 130, { align: 'center' });
  doc.text(dateStr, pageWidth / 2, 140, { align: 'center' });

  doc.text('country-compare.com', pageWidth / 2, 160, { align: 'center' });

  if (!fullReport) {
    doc.setFontSize(10);
    doc.setTextColor(252, 211, 77); // amber-300
    doc.text('FREE VERSION - 5 indicators included', pageWidth / 2, 180, { align: 'center' });
    doc.text('Upgrade to Pro for all 50 indicators', pageWidth / 2, 188, { align: 'center' });
  } else {
    doc.setFontSize(10);
    doc.setTextColor(191, 219, 254);
    doc.text(`${indicators.length} indicators included`, pageWidth / 2, 180, { align: 'center' });
  }

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Data source: World Bank Open Data', pageWidth / 2, pageHeight - 20, { align: 'center' });

  // --- Executive Summary Page ---
  doc.addPage();
  doc.setTextColor(31, 41, 55);
  doc.setFontSize(20);
  doc.text('Executive Summary', 20, 25);

  doc.setDrawColor(59, 130, 246);
  doc.setLineWidth(0.5);
  doc.line(20, 30, pageWidth - 20, 30);

  // Key stats table
  const keyIndicatorIds = ['NY.GDP.MKTP.CD', 'SP.POP.TOTL', 'SL.UEM.TOTL.ZS', 'FP.CPI.TOTL.ZG', 'SP.DYN.LE00.IN'];
  const summaryRows: string[][] = [];

  for (const indId of keyIndicatorIds) {
    const result = allData.find((d) => d.indicator.id === indId);
    if (!result) continue;
    const row: string[] = [result.indicator.name];
    for (const code of countryCodes) {
      const countryData = result.countries[code];
      if (!countryData) {
        row.push('N/A');
        continue;
      }
      const withValues = countryData.data.filter((d) => d.value !== null);
      const latest = withValues.length > 0 ? withValues[withValues.length - 1] : null;
      row.push(latest ? formatValue(latest.value, result.indicator.format) : 'N/A');
    }
    summaryRows.push(row);
  }

  const summaryHeaders = ['Indicator', ...countryCodes.map((c) => countryNames[c] || c)];

  autoTable(doc, {
    startY: 38,
    head: [summaryHeaders],
    body: summaryRows,
    theme: 'grid',
    styles: { fontSize: 9, cellPadding: 4 },
    headStyles: { fillColor: [30, 64, 175], textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } },
    margin: { left: 20, right: 20 },
  });

  // --- Indicator Detail Pages ---
  for (const result of allData) {
    doc.addPage();
    doc.setTextColor(31, 41, 55);
    doc.setFontSize(16);
    doc.text(result.indicator.name, 20, 25);

    doc.setDrawColor(209, 213, 219);
    doc.setLineWidth(0.3);
    doc.line(20, 30, pageWidth - 20, 30);

    // Collect all years
    const allYears = Array.from(
      new Set(
        Object.values(result.countries).flatMap((c) => c.data.map((d) => d.year))
      )
    ).sort();

    // Filter years based on tier
    const years = fullReport ? allYears : allYears.filter((y) => parseInt(y) >= 2014);

    const tableHeaders = ['Year', ...countryCodes.map((c) => countryNames[c] || c)];
    const tableRows: string[][] = years.map((year) => {
      const row: string[] = [year];
      for (const code of countryCodes) {
        const countryData = result.countries[code];
        if (!countryData) {
          row.push('N/A');
          continue;
        }
        const point = countryData.data.find((d) => d.year === year);
        row.push(point ? formatValue(point.value, result.indicator.format) : 'N/A');
      }
      return row;
    });

    autoTable(doc, {
      startY: 36,
      head: [tableHeaders],
      body: tableRows,
      theme: 'striped',
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: [30, 64, 175], textColor: [255, 255, 255], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      columnStyles: { 0: { fontStyle: 'bold', cellWidth: 20 } },
      margin: { left: 20, right: 20 },
    });
  }

  // Add watermark to all pages (except cover) for free users
  if (!fullReport) {
    const totalPages = doc.getNumberOfPages();
    for (let i = 2; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setTextColor(200, 200, 200);
      doc.setFontSize(30);
      doc.text('FREE VERSION', pageWidth / 2, pageHeight / 2, {
        align: 'center',
        angle: 45,
      });
    }
  }

  // Add footer to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(148, 163, 184);
    if (i > 1) {
      doc.text('Data source: World Bank Open Data | country-compare.com', pageWidth / 2, pageHeight - 8, { align: 'center' });
      doc.text(`Page ${i} of ${totalPages}`, pageWidth - 20, pageHeight - 8, { align: 'right' });
    }
  }

  const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
  const filename = `CountryCompare_${countryCodes.join('_vs_')}_Report_${new Date().getFullYear()}.pdf`;

  return new NextResponse(pdfBuffer, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Cache-Control': 'no-store',
    },
  });
}
